hero1:
  name: 安琪拉
  word: 火焰是我最喜欢的玩具
  Hp: 445.5

hero2: { name: 安琪拉, word: 火焰是我最喜欢的玩具, Hp: 445.5 }

heros_name:
  - 安琪拉
  - 黄忠
  - 小乔

heros:
  - name: 黄忠
    word: 周日被我射熄火了
    Hp: 440
heros_name_list:
  - - 安琪拉
    - 黄忠
    - 小乔

test:
  name: login_case1
  request:
    url: http://X.X.X.X/api/v1/login/
    method: POST
    headers:
      Content-Type: application/json
    json:
      username: test
      password: 123456
      heros:
        - name: 黄忠
          word: 周日被我射熄火了
          Hp: 440
mobile_belong: {shouji: 13456755448 , appkey: 0c818521d38759e1}
#  -[13456755448,0c818521d38759e1]

mobile_belong_post:
# 手机号，appkey
  - [13456755448,0c818521d38759e1]



mobile_belong_get:
# 手机号，appkey
  - [ 13456755448, 0c818521d38759e1 ]
  - [ 13012340987, 0c818521d38759e1 ]
